### ISSUE TITLE
slack permissions to skills

### ISSUE THREAD

**Issue by ronendayan** [opsdroid/connector-slack#12]
Hi,
How can i set permissions to skills, To allow User A to use specific skill and not allow User B ?

**Comment by jacobtomlinson** [comment]
Thanks for raising this issue @ronendayan.

I'm afraid there is nothing in opsdroid which specifically does what you're asking. However you could compare the username in the `message` object to a whitelist. You could also make this a config option so you don't have to edit your code to update the list. 

Here's an example

```python
from opsdroid.matchers import match_regex

@match_regex(r"Hello world")
async def hello_world_skill(opsdroid, config, message):
    if message.user not in config.get("whitelist"):
        await message.respond("Sorry you are not allowed to do this")
        return
    
    # Do some stuff
```

```yaml
# ...your main config stuff...

skills:
  - name: myskill
    path: /path/to/my/skill
    whitelist:
      - alice
      - bob
```

In this example if anyone other than `alice` or `bob` tries to use the skill they will get a warning and the skill will exit.
